import UIKit

class TermsConditionsViewController: UIViewController {

    @IBOutlet weak var ScrollView: UIScrollView!
    @IBOutlet weak var termsLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        termsLabel.text = """
        Privacy Policy
        Last updated: August 29, 2024

        This Privacy Policy describes Our policies and procedures on the collection, use, and disclosure of Your information when You use the Service and informs You about Your privacy rights and how the law protects You. We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

        Interpretation and Definitions
        Interpretation
        The words with initial capital letters have meanings defined under the following conditions. These definitions shall have the same meaning regardless of whether they appear in singular or plural form.

        Definitions
        For the purposes of this Privacy Policy:

        Account: A unique account created for You to access our Service or parts of our Service.
        Affiliate: An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest, or other securities entitled to vote for the election of directors or other managing authority.
        Application: Refers to Skiliket, the software program provided by the Company.
        Company (referred to as "the Company", "We", "Us" or "Our" in this Agreement): Refers to Skiliket.
        Country: Refers to Alberta, Canada.
        Device: Any device that can access the Service, such as a computer, cellphone, or digital tablet.
        Personal Data: Any information that relates to an identified or identifiable individual.
        Service: Refers to the Application.
        Service Provider: Any natural or legal person who processes data on behalf of the Company.
        Usage Data: Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (e.g., the duration of a page visit).
        You: The individual accessing or using the Service, or the company or other legal entity on behalf of which such an individual is accessing or using the Service, as applicable.
        Collecting and Using Your Personal Data

        Types of Data Collected

        Personal Data: While using Our Service, we may ask You to provide us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        Email address
        First name and last name
        Location
        Camera access
        Use of Your Personal Data

        The Company may use Personal Data for the following purposes:

        To provide and maintain our Service, including to monitor the usage of our Service.
        To manage Your Account: Manage Your registration as a user of the Service.
        For the performance of a contract: To fulfill a purchase contract for products, items, or services You have purchased or any other contract with Us.
        To contact You: Via email, telephone calls, SMS, or other electronic communications regarding updates or informational communications related to functionalities, products, or contracted services.
        To provide You with news, special offers, and general information about similar goods, services, and events unless You have opted not to receive such information.
        To manage Your requests: Attend and manage Your requests to Us.
        For business transfers: To evaluate or conduct a merger, restructuring, or sale of assets.
        For other purposes: Such as data analysis, identifying usage trends, and improving our Service, products, services, and user experience.
        Retention and Transfer of Your Personal Data

        The Company will retain Your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. Your data, including Personal Data, may be transferred to computers located outside of Your state, province, country, or other governmental jurisdiction.

        Delete Your Personal Data

        You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.

        Disclosure of Your Personal Data

        We may disclose Your Personal Data under certain circumstances, such as to comply with a legal obligation or to protect against legal liability.

        Security of Your Personal Data

        We strive to use commercially acceptable means to protect Your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.

        Children's Privacy

        Our Service does not knowingly collect personally identifiable information from anyone under the age of 13 without parental consent.

        Links to Other Websites

        Our Service may contain links to other websites that are not operated by Us.

        Changes to this Privacy Policy

        We may update Our Privacy Policy from time to time.

        Contact Us

        If you have any questions about this Privacy Policy, you can contact us by email: Obmiguel26@gmail.com
        """

        termsLabel.sizeToFit()

        ScrollView.contentSize = CGSize(width: termsLabel.frame.width, height: termsLabel.frame.height)
    }
}
